[feature request] Adicionar sistema de pontuação para usuários
unb-mds/2023-2-JuizVirtual pull request #106
Opened 2023-12-01 19:44 UTC by thegm445

# O que este PR introduz?

Closes #105

## Checklist

Por favor, cheque se seu PR atende aos seguintes requisitos:

- [ ] Eu atualizei a documentação de acordo (se necessário).
- [ ] Eu adicionei testes para cobrir minhas mudanças (se necessário).
- [ ] Todos os novos e existentes testes passaram.
- [ ] Meu código segue o estilo de código deste projeto.

## Tipo de PR

Que tipo de mudança este PR introduz?

- [ ] Correção de bug
- [ ] Feature request
- [ ] Atualização na documentação
- [ ] Atualização no estilo do código (formatação, variáveis locais, etc.)
- [ ] Refatoração (sem mudanças funcionais, sem mudanças na API)
- [ ] Atualizações de dependências
- [ ] Mudanças relacionadas a CI/CD
- [ ] Chore (mudanças não relacionadas a código)
- [ ] Mudanças relacionadas a build (e.g. Dockerfile, pyproject.toml, etc.)

## Este PR introduz uma mudança que quebra a compatibilidade?

- [ ] Sim
- [ ] Não

## Outras informações (screenshots, detalhes, etc.)

2023-12-01 21:53 UTC, bitterteriyaki requested changes

2023-12-01 23:44 UTC, thegm445 commented on apps/tasks/views.py
> +        .exclude(id=submission.id)
Estou excluindo apenas a submissão atual, podendo apenas usar o método exists(), sem me preocupar se estou verificando a existência da atual submissão.

2023-12-01 23:47 UTC, thegm445 commented on apps/tasks/views.py
> +        if not has_been_accepted:
A aparência do código ficaria ruim. Veja commit mais recente.

2023-12-02 00:51 UTC, bitterteriyaki requested changes

2023-12-02 00:51 UTC, bitterteriyaki commented on apps/tasks/views.py
> +        .exclude(id=submission.id)
Trocar o nome da variável para `has_already_scored`.

2023-12-02 01:03 UTC, bitterteriyaki requested changes

2023-12-02 01:03 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +        self.assertEqual(self.user.score, self.task.score)
Remover o espaço entre essas duas linhas de código para melhorar legibilidade.

2023-12-02 01:10 UTC, bitterteriyaki commented on apps/tasks/views.py
> +        if not has_been_accepted:
Qualquer coisa, você pode colocar a primeira expressão em uma variável. Algo tipo:
```py
is_accepted = submissions.status == SubmissionStatus.ACCEPTED

if is_accepted and not has_already_scored:
    ...
```

2023-12-02 02:23 UTC, bitterteriyaki requested changes

2023-12-02 02:23 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +        handle_submission(
Usar o `apply` aqui.

2023-12-02 02:53 UTC, bitterteriyaki requested changes
Falta refletir essas mudanças na página de administração e na página de perfil de usuário.

2023-12-05 21:48 UTC, bitterteriyaki requested changes

2023-12-05 21:48 UTC, bitterteriyaki commented on apps/users/tests.py
> +        )  # Adicione 'score' aqui
Remover esse comentário.

2023-12-05 21:48 UTC, bitterteriyaki commented on apps/users/tests.py
> +                    ),  # Adicione 'score' aqui
Remover esse comentário.

2023-12-05 22:35 UTC, thegm445 commented on apps/tasks/views.py
> +        if not has_been_accepted:
Corrigido!

2023-12-05 22:36 UTC, thegm445 commented on apps/users/tests.py
> +                    ),  # Adicione 'score' aqui
Removidos :+1:

2023-12-06 02:15 UTC, bitterteriyaki approved these changes
LGTM, TYVM.

2023-12-06 02:16 UTC, merged