[feature request] Colocar cores na tabela de submissão de acordo como o status
unb-mds/2023-2-JuizVirtual pull request #110
Opened 2023-12-07 10:48 UTC by LuizaMaluf

# O que este PR introduz?

## Checklist

Por favor, cheque se seu PR atende aos seguintes requisitos:

- [ ] Eu atualizei a documentação de acordo (se necessário).
- [ ] Eu adicionei testes para cobrir minhas mudanças (se necessário).
- [ ] Todos os novos e existentes testes passaram.
- [ ] Meu código segue o estilo de código deste projeto.

## Tipo de PR

Que tipo de mudança este PR introduz?

- [ ] Correção de bug
- [ ] Feature request
- [ ] Atualização na documentação
- [ ] Atualização no estilo do código (formatação, variáveis locais, etc.)
- [ ] Refatoração (sem mudanças funcionais, sem mudanças na API)
- [ ] Atualizações de dependências
- [ ] Mudanças relacionadas a CI/CD
- [ ] Chore (mudanças não relacionadas a código)
- [ ] Mudanças relacionadas a build (e.g. Dockerfile, pyproject.toml, etc.)

## Este PR introduz uma mudança que quebra a compatibilidade?

- [ ] Sim
- [ ] Não

## Outras informações (screenshots, detalhes, etc.)

2023-12-09 04:15 UTC, bitterteriyaki requested changes

2023-12-09 04:15 UTC, bitterteriyaki commented on templates/submissions/list.html
> +        <tr class ="{% if submission.status == 'AC' %}success{% elif submission.status == 'WA' or submission.status == 'MLE' or submission.status == 'TLE' or submission.status == 'RE' or submission.s
Tenta dividir essa tag em múltiplas linhas para não ficar uma linha gigante.

2023-12-10 14:36 UTC, bitterteriyaki approved these changes
LGTM, TYVM.

2023-12-10 14:40 UTC, thegm445 approved these changes
Looks Good To Me, Thank You Very Much.

2023-12-10 14:40 UTC, merged